### PR TITLE
Update minesweeper.py

### PR DESCRIPTION
**Pull request by bangyen**

### CODE REVIEW

**Comment by hopg** [comment]
Thanks very much for taking a look at my code! I have made a few comments below 👍 

- I like the new instantiation of which board to create based on the difficulty
- Very nice technique on displaying the board however, I have amended this by adding in an if statement so that it replicates the current board layout
- The `mine_pos` method in the `Mines` class is designed to show the mines as it is used for debugging
- I will also add in space formatting 

Please check out the latest commit if you have time. 

Once again, thank you very much for spending time on my code, I really appreciate it!

**Comment by bangyen** [comment]
Whoops, my bad in regards to the extra `print` statement. Also, since you've incorporated my changes in a new commit, should I just delete my PR? 😕

**Comment by hopg** [comment]
Ah my bad, new to github and didn’t realise. 

Tell you what, I could merge a new PR, would that suit? 😄

**Comment by bangyen** [comment]
No worries! I threw together a quick PR. When I'm not as busy, I'll try to work on the code some more. 😄

**Comment by hopg** [comment]
Nice one, I’ll close this!

**Pull request closed without merging**
